const productos = [
    {
        id: 0,
        image: "https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_468,w_500/c_pad,h_468,w_500/l_sale-badge,fl_relative,w_0.12,g_north_west,e_sharpen/l_bypetco-badge,fl_relative,w_0.20,g_south_east,e_sharpen/3396557-center-1",
        title: "More and Merrier Pickles Cat Toy, Pack of 2",
        price: 5.49,
    },
    {
        id: 1,
        image: "https://static.miscota.com/media/1/photos/products/503053/OIeP-wZY-630f18d38916a_g.jpg",
        title: "FuzzYard Sudadera Turtle Teddy Rosa para Perro",
        price: 21.24,
    },
    {
        id: 2,
        image: "https://assets.petco.com/petco/image/upload/c_pad,dpr_1.0,f_auto,q_auto,h_468,w_500/c_pad,h_468,w_500/l_sale-badge,fl_relative,w_0.12,g_north_west,e_sharpen/l_bypetco-badge,fl_relative,w_0.20,g_south_east,e_sharpen/3602411-center-10",
        title: "More and Merrier Cozy Fairisle Tunnel Cat Toy",
        price: 11.16,
    },
    {
        id: 3,
        image: "https://tractive.com/assets/image/dpr_2,w_1200/shop-frontend/pages/product-detail-page/product-hero/product-images/trnjabl/tractive-gps-dog-4-blue-packaging-es.webp",
        title: "Localizador GPS para perros",
        price: 16.95,
    },    
    {
        id: 4,
        image: "https://static.miscota.com/media/1/photos/products/042657/88-63627821e9590_g.png",
        title: "Inodorina Spray Desodorante de Talco para Perros y Gatos",
        price: 6.15,
    },    
    {
        id: 5,
        image: "https://m.media-amazon.com/images/I/71i87T0k44L._AC_SX679_.jpg",
        title: "Sanicat Active Arena De Gato, Ultra Aglomerante, Aroma de Flor de Loto, 6L",
        price: 12.79,
    },
    {
        id: 6,
        image: "https://static.miscota.com/media/1/photos/products/049252/49252-24802_0_g.jpeg",
        title: "Dermoscent Bálsamo Bio Balm Reparador para Almohadillas y Trufa",
        price: 17.95,
    },
    {
        id: 7,
        image: "https://static.miscota.com/media/1/photos/products/049144/49144-adofilm_0_g.jpg",
        title: "Calier Pomada Ado Film Protectora y Cicatrizante",
        price: 11.95,
    },
    {
        id: 8,
        image: "https://static.miscota.com/media/1/photos/products/069333/69333-5414365062705_1_g.jpg",
        title: "Duvo Plus Albornoz Perro Microfibra Azul",
        price: 20.92,
    },
    {
        id: 9,
        image: "https://m.media-amazon.com/images/I/61nz0M6JqtL._AC_SX679_.jpg",
        title: "PETKIT Pura X Caja de Arena Intelligent autolimpiable, XSecure/Eliminación de olores/Control de App, Caja de Arena automática Buena para Varios Gatos",
        price: 200.92,
    },
    {
        id: 10,
        image: "https://m.media-amazon.com/images/I/719DcxvJqZL._AC_SX679_.jpg",
        title: "Cuello protector hinchable para perros y gatos. De tacto suave y con hebilla ajustable.",
        price: 20.92,
    },
    {
        id: 11,
        image: "https://m.media-amazon.com/images/I/61dR+sm-RGL._AC_SX679_.jpg",
        title: "PETKIT Mochila para Gatos, Mochila de Viaje para Cachorros, Ventilador Incorporado y Sistema de iluminación, Mochila para Transporte de Mascotas Bien Ventilada, Ligera y Cómoda (Verde)",
        price: 20.92,
    },
    {
        id: 12,
        image: "https://m.media-amazon.com/images/I/61ZEISQCcJS._AC_SX679_.jpg",
        title: "CAT DANCER Juguete",
        price: 5.49,
    },
    {
        id: 13,
        image: "https://cdn.shopify.com/s/files/1/1511/7434/products/tuft-paw-milo-cat-tree-2_f1257422-e1e7-45d8-ac8d-f332f60f607d.jpg?crop=center&height=540&v=1610405756&width=540",
        title: "Milo Cat Tree",
        price: 500.49,
    },
    {
        id: 14,
        image: "https://www.catastrophicreations.com/wp-content/uploads/2015/06/LR11NANT_GalleryWCat2_DelRaceway_1500x1000.jpg",
        title: "Deluxe Raceway Cat Hammock",
        price: 125.50,
    },
    {
        id: 15,
        image: "https://people.com/thmb/z94KWXNj_HBT596Ap2jQJ3peqiU=/2000x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(877x0:879x2):format(webp)/PetAwards_25-a5500713802148d59d882dcd0e8ac6c7.jpg",
        title: "Whistle GO Explore GPS Tracker",
        price: 150.20,
    },
]